(()=>{"use strict";
const PROFILE_KEY="f2math_v50_profiles",ACTIVE_KEY="f2math_v50_active_student";
const CHAPTERS=["Pattern and Sequences","Factorisation and Algebraic Fractions","Algebraic Formulae","Polygons","Circles","Three-Dimensional Geometrical Shapes","Coordinates","Graphs of Functions","Speed and Acceleration","Gradient of a Straight Line","Isometric Transformations","Measures of Central Tendencies","Simple Probability"];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function profiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||"{}")||{}}catch{return {}}}
function active(){const name=localStorage.getItem(ACTIVE_KEY),all=profiles();return name?all[name]||null:null}
function save(p){const all=profiles();all[p.name]=p;localStorage.setItem(PROFILE_KEY,JSON.stringify(all))}
function ensure(p){p.chapterStats??={};p.masteryRewards??={};return p}
function chapterId(){const text=$("#chapterTitle")?.textContent||"";const m=text.match(/Chapter\s+(\d+)/i);return m?Number(m[1]):null}
function statsFor(p,id){p.chapterStats[id]??={attempts:0,correct:0,bestCombo:0};return p.chapterStats[id]}
function stars(p,id){const s=statsFor(p,id),boss=!!p.bossWins?.[id],accuracy=s.attempts?Math.round(s.correct/s.attempts*100):0;let n=0;if(s.correct>=1)n=1;if(boss)n=2;if(boss&&accuracy>=80&&s.attempts>=3)n=3;return {n,accuracy,s}}
function inject(){const row=$("#lobbyView .topbar .row");if(row&&!$("#masteryBtn")){const b=document.createElement("button");b.id="masteryBtn";b.className="btn secondary";b.textContent="Mastery";row.insertBefore(b,$("#teacherLobbyBtn")||$("#switchBtn"));b.addEventListener("click",open)}if(!$("#masteryView")){const sec=document.createElement("section");sec.id="masteryView";sec.className="panel hidden";sec.innerHTML='<div class="topbar"><div><strong>Chapter Mastery</strong><div id="masterySummary" class="muted"></div></div><button id="masteryBackBtn" class="btn secondary">Back to Chapters</button></div><div id="masteryGrid" class="mastery-grid"></div>';$("main.shell").insertBefore(sec,$("#gameView"));$("#masteryBackBtn").addEventListener("click",back)}}
function hide(){["loginView","lobbyView","heroView","petView","missionView","achievementView","teacherView","shopView","chestView","gameView","wrongBookView"].forEach(id=>$("#"+id)?.classList.add("hidden"))}
function open(){const p=active();if(!p)return;hide();$("#masteryView").classList.remove("hidden");render()}
function back(){$("#masteryView")?.classList.add("hidden");$("#lobbyView")?.classList.remove("hidden");decorateChapters()}
function render(){const p=ensure(active());if(!p)return;let total=0;const cards=CHAPTERS.map((name,i)=>{const id=i+1,{n,accuracy,s}=stars(p,id);total+=n;const claimed=!!p.masteryRewards[id],can=n===3&&!claimed;return `<article class="mastery-card stars-${n}"><div class="mastery-top"><strong>Chapter ${id}</strong><span>${"★".repeat(n)}${"☆".repeat(3-n)}</span></div><p>${name}</p><div class="mastery-stats"><b>${s.correct}/${s.attempts} correct</b><b>${accuracy}% accuracy</b><b>Best combo ${s.bestCombo||0}</b></div><small>1★ answer correctly · 2★ defeat Boss · 3★ Boss + 80% accuracy</small><button class="btn ${claimed?'secondary':''}" data-mastery-claim="${id}" ${can?'':'disabled'}>${claimed?'Reward Claimed':n===3?'Claim 30 Coins':'Reach 3 Stars'}</button></article>`}).join("");$("#masterySummary").textContent=`${total}/39 stars earned`;$("#masteryGrid").innerHTML=cards;$$('[data-mastery-claim]').forEach(b=>b.addEventListener('click',()=>claim(Number(b.dataset.masteryClaim))))}
function claim(id){const p=ensure(active());if(!p||stars(p,id).n<3||p.masteryRewards[id])return;p.coins=(p.coins||0)+30;p.masteryRewards[id]=true;save(p);const coins=$("#playerCoins");if(coins)coins.textContent=p.coins;render()}
function track(){const target=$("#feedback");if(!target)return;let last="";new MutationObserver(()=>{const text=target.textContent.trim();if(!text||text===last)return;last=text;const id=chapterId(),p=active();if(!id||!p)return;const s=statsFor(ensure(p),id);if(/attacks|Correct|Critical/i.test(text)){s.attempts++;s.correct++;s.bestCombo=Math.max(s.bestCombo||0,Number($("#comboValue")?.textContent||0));save(p)}else if(/counterattacks|Not yet|TRY AGAIN/i.test(text)){s.attempts++;save(p)}},{childList:true,subtree:true,characterData:true})}
function decorateChapters(){const p=active();if(!p)return;$$('[data-chapter]').forEach(card=>{const id=Number(card.dataset.chapter),n=stars(ensure(p),id).n;let badge=card.querySelector('.mastery-badge');if(!badge){badge=document.createElement('span');badge.className='mastery-badge';card.appendChild(badge)}badge.textContent=`${"★".repeat(n)}${"☆".repeat(3-n)}`})}
window.addEventListener("DOMContentLoaded",()=>{document.title="F2 Math Hero V51.4";const h=document.querySelector('.hero h1');if(h)h.textContent='F2 Math Hero V51.4';inject();track();const grid=$("#chapterGrid");if(grid)new MutationObserver(decorateChapters).observe(grid,{childList:true});setTimeout(decorateChapters,400)})
})();