(()=>{"use strict";
const PROFILE_KEY="f2math_v50_profiles",ACTIVE_KEY="f2math_v50_active_student";
const $=s=>document.querySelector(s);
function profiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||"{}")||{}}catch{return {}}}
function activeName(){return localStorage.getItem(ACTIVE_KEY)||""}
function stamp(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kuala_Lumpur",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date()).replace(/[,: ]/g,"-")}
function download(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function status(text,kind="ok"){const el=$("#backupStatus");if(!el)return;el.textContent=text;el.className=`backup-status ${kind}`}
function inject(){const loginRow=$("#loginView .row");if(loginRow&&!$("#backupLoginBtn")){const b=document.createElement("button");b.id="backupLoginBtn";b.className="btn secondary";b.textContent="Backup Center";loginRow.appendChild(b);b.addEventListener("click",open)}const lobbyRow=$("#lobbyView .topbar .row");if(lobbyRow&&!$("#backupBtn")){const b=document.createElement("button");b.id="backupBtn";b.className="btn secondary";b.textContent="Backup";lobbyRow.insertBefore(b,$("#teacherLobbyBtn")||$("#switchBtn"));b.addEventListener("click",open)}if(!$("#backupView")){const section=document.createElement("section");section.id="backupView";section.className="panel hidden";section.innerHTML='<div class="topbar"><div><strong>Backup & Restore</strong><div class="muted">Move student progress between devices or keep a safety copy.</div></div><button id="backupBackBtn" class="btn secondary">Back</button></div><div class="backup-grid"><article class="backup-card"><strong>Current Student</strong><p>Export only the active student profile.</p><button id="exportStudentBtn" class="btn">Export Student</button></article><article class="backup-card"><strong>All Students</strong><p>Export every local profile, ranking and learning record.</p><button id="exportAllBtn" class="btn">Export All</button></article><article class="backup-card"><strong>Restore Backup</strong><p>Import a JSON backup. Existing students with the same name will be replaced.</p><label class="backup-file">Choose JSON<input id="importBackupInput" type="file" accept="application/json,.json"></label></article></div><div id="backupStatus" class="backup-status">No backup action yet.</div>';$("main.shell").insertBefore(section,$("#gameView"));$("#backupBackBtn").addEventListener("click",back);$("#exportStudentBtn").addEventListener("click",exportStudent);$("#exportAllBtn").addEventListener("click",exportAll);$("#importBackupInput").addEventListener("change",importBackup)}}
function hide(){["loginView","lobbyView","heroView","petView","missionView","achievementView","teacherView","gameView","wrongBookView","shopView","chestView","masteryView","leaderboardView","adaptiveView"].forEach(id=>$("#"+id)?.classList.add("hidden"))}
function open(){hide();$("#backupView")?.classList.remove("hidden");const count=Object.keys(profiles()).length;status(`${count} local student profile${count===1?"":"s"} available.`)}
function back(){$("#backupView")?.classList.add("hidden");if(activeName())$("#lobbyView")?.classList.remove("hidden");else $("#loginView")?.classList.remove("hidden")}
function exportStudent(){const name=activeName(),all=profiles(),p=name?all[name]:null;if(!p)return status("No active student to export.","bad");download(`f2-math-hero-${name}-${stamp()}.json`,{app:"F2 Math Hero",version:"51.7",type:"student",exportedAt:new Date().toISOString(),activeStudent:name,profiles:{[name]:p}});status(`Exported ${name}.`)}
function exportAll(){const all=profiles(),count=Object.keys(all).length;if(!count)return status("There are no student records to export.","bad");download(`f2-math-hero-all-${stamp()}.json`,{app:"F2 Math Hero",version:"51.7",type:"all",exportedAt:new Date().toISOString(),activeStudent:activeName(),profiles:all});status(`Exported ${count} student profiles.`)}
function importBackup(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result||""));if(data.app!=="F2 Math Hero"||!data.profiles||typeof data.profiles!=="object")throw new Error("Invalid backup format");const incoming=data.profiles,current=profiles(),names=Object.keys(incoming);if(!names.length)throw new Error("Backup has no student profiles");names.forEach(name=>{const p=incoming[name];if(!p||typeof p!=="object")throw new Error(`Invalid profile: ${name}`);current[name]={...p,name:p.name||name}});localStorage.setItem(PROFILE_KEY,JSON.stringify(current));if(data.activeStudent&&current[data.activeStudent])localStorage.setItem(ACTIVE_KEY,data.activeStudent);status(`Restored ${names.length} profile${names.length===1?"":"s"}. Reloading...`);setTimeout(()=>location.reload(),900)}catch(err){status(err.message||"Could not restore this backup.","bad")}finally{e.target.value=""}};reader.onerror=()=>status("Could not read the selected file.","bad");reader.readAsText(file)}
window.addEventListener("DOMContentLoaded",()=>{document.title="F2 Math Hero V51.7";const h=$(".hero h1");if(h)h.textContent="F2 Math Hero V51.7";inject()});
})();