(()=>{"use strict";
const PROFILE_KEY="f2math_v50_profiles",ACTIVE_KEY="f2math_v50_active_student";
const $=s=>document.querySelector(s);
const CHAPTERS=["Pattern and Sequences","Factorisation and Algebraic Fractions","Algebraic Formulae","Polygons","Circles","Three-Dimensional Geometrical Shapes","Coordinates","Graphs of Functions","Speed and Acceleration","Gradient of a Straight Line","Isometric Transformations","Measures of Central Tendencies","Simple Probability"];
function profiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||"{}")||{}}catch{return {}}}
function active(){const name=localStorage.getItem(ACTIVE_KEY),all=profiles();return name?all[name]||null:null}
function stars(p,id){const s=p.masteryStars?.[id];if(Number.isFinite(s))return Math.max(0,Math.min(3,s));const stat=p.chapterStats?.[id]||{};const attempts=stat.attempts||0,correct=stat.correct||0,accuracy=attempts?correct/attempts:0,boss=!!p.bossWins?.[id];return correct>0?boss?(accuracy>=.8?3:2):1:0}
function grade(acc){return acc>=90?"A":acc>=80?"B":acc>=65?"C":acc>=50?"D":"E"}
function hide(){["loginView","lobbyView","heroView","petView","missionView","achievementView","teacherView","gameView","wrongBookView","shopView","chestView","masteryView","leaderboardView","adaptiveView","backupView"].forEach(id=>$("#"+id)?.classList.add("hidden"))}
function inject(){const row=$("#lobbyView .topbar .row");if(row&&!$("#reportBtn")){const b=document.createElement("button");b.id="reportBtn";b.className="btn secondary";b.textContent="Report Card";row.insertBefore(b,$("#teacherLobbyBtn")||$("#switchBtn"));b.addEventListener("click",open)}if(!$("#reportView")){const section=document.createElement("section");section.id="reportView";section.className="panel hidden";section.innerHTML='<div class="topbar"><div><strong>Student Report Card</strong><div id="reportSummary" class="muted"></div></div><div class="row"><button id="printReportBtn" class="btn">Print Report</button><button id="reportBackBtn" class="btn secondary">Back to Chapters</button></div></div><div id="reportContent"></div>';$("main.shell").insertBefore(section,$("#gameView"));$("#reportBackBtn").addEventListener("click",back);$("#printReportBtn").addEventListener("click",()=>window.print())}}
function open(){const p=active();if(!p)return;hide();$("#reportView").classList.remove("hidden");render(p)}
function back(){$("#reportView")?.classList.add("hidden");$("#lobbyView")?.classList.remove("hidden")}
function render(p){const attempts=p.stats?.attempts||0,correct=p.stats?.correct||0,wrong=p.stats?.wrong||0,acc=attempts?Math.round(correct/attempts*100):0,bosses=Object.values(p.bossWins||{}).filter(Boolean).length,totalStars=Array.from({length:13},(_,i)=>stars(p,i+1)).reduce((a,b)=>a+b,0),wrongCount=p.wrongBook?.length||0;
$("#reportSummary").textContent=`${p.name} · Overall Grade ${grade(acc)} · ${acc}% accuracy`;
const strongest=[],priority=[];
const rows=CHAPTERS.map((title,i)=>{const id=i+1,stat=p.chapterStats?.[id]||{},a=stat.attempts||0,c=stat.correct||0,rate=a?Math.round(c/a*100):0,s=stars(p,id),boss=!!p.bossWins?.[id];if(a&&rate>=80)strongest.push(`Chapter ${id}`);if(!a||rate<60||!boss)priority.push(`Chapter ${id}`);return `<tr><td>${id}</td><td>${title}</td><td>${c}/${a}</td><td>${a?rate+"%":"No data"}</td><td>${"★".repeat(s)}${"☆".repeat(3-s)}</td><td>${boss?"Defeated":"Pending"}</td></tr>`}).join("");
$("#reportContent").innerHTML=`<div class="report-hero"><div><span class="report-kicker">F2 MATH HERO</span><h2>${p.name}</h2><p>Progress report generated ${new Date().toLocaleDateString("en-MY")}</p></div><div class="report-grade">${grade(acc)}</div></div><div class="report-metrics"><article><strong>${acc}%</strong><span>Accuracy</span></article><article><strong>${correct}</strong><span>Correct</span></article><article><strong>${wrong}</strong><span>Wrong</span></article><article><strong>${bosses}/13</strong><span>Bosses</span></article><article><strong>${totalStars}/39</strong><span>Mastery Stars</span></article><article><strong>${wrongCount}</strong><span>Wrong Book</span></article></div><div class="report-insights"><article><strong>Strengths</strong><p>${strongest.length?strongest.slice(0,5).join(", "):"More completed practice is needed before strengths can be identified."}</p></article><article><strong>Priority Practice</strong><p>${priority.length?priority.slice(0,5).join(", "):"All chapters are currently on track."}</p></article></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Ch.</th><th>Topic</th><th>Correct</th><th>Accuracy</th><th>Mastery</th><th>Boss</th></tr></thead><tbody>${rows}</tbody></table></div>`}
window.addEventListener("DOMContentLoaded",()=>{document.title="F2 Math Hero V51.8";const h=$(".hero h1");if(h)h.textContent="F2 Math Hero V51.8";inject()});
})();