(()=>{"use strict";
const PROFILE_KEY="f2math_v50_profiles",ACTIVE_KEY="f2math_v50_active_student";
const $=s=>document.querySelector(s);
const ITEMS=[
{id:"bronze-blade",name:"Bronze Blade",icon:"⚔️",type:"gear",price:35,desc:"Equip to gain +2 bonus XP after every correct answer.",xp:2,coins:0},
{id:"coin-charm",name:"Coin Charm",icon:"🪙",type:"gear",price:50,desc:"Equip to gain +1 bonus coin after every correct answer.",xp:0,coins:1},
{id:"scholar-crown",name:"Scholar Crown",icon:"👑",type:"gear",price:90,desc:"Equip to gain +1 XP and +1 coin after every correct answer.",xp:1,coins:1},
{id:"xp-potion",name:"XP Potion",icon:"🧪",type:"consumable",price:20,desc:"Use immediately to receive 40 player XP.",playerXp:40},
{id:"hero-manual",name:"Hero Training Manual",icon:"📕",type:"consumable",price:30,desc:"Use immediately to receive 35 Hero XP.",heroXp:35},
{id:"pet-snack",name:"Pet Power Snack",icon:"🍖",type:"consumable",price:25,desc:"Use immediately to receive 25 Pet XP.",petXp:25}
];
function profiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||"{}")||{}}catch{return {}}}
function active(){const name=localStorage.getItem(ACTIVE_KEY),all=profiles();return name?all[name]||null:null}
function save(p){const all=profiles();all[p.name]=p;localStorage.setItem(PROFILE_KEY,JSON.stringify(all));updateLobby(p)}
function ensure(p){p.inventory??=[];p.equippedGear??=null;p.shopPurchases??=0;return p}
function updateLobby(p){const xp=$("#playerXp"),coins=$("#playerCoins");if(xp)xp.textContent=p.xp||0;if(coins)coins.textContent=p.coins||0;const old=$("#activeGearLabel");const item=ITEMS.find(x=>x.id===p.equippedGear);if(old)old.textContent=item?`${item.icon} Equipped: ${item.name}`:"No equipment selected"}
function inject(){const row=$("#lobbyView .topbar .row");if(row&&!$("#shopBtn")){const b=document.createElement("button");b.id="shopBtn";b.className="btn secondary";b.textContent="Shop";row.insertBefore(b,$("#teacherLobbyBtn")||$("#switchBtn"));b.addEventListener("click",openShop)}const pet=$("#activePetLabel");if(pet&&!$("#activeGearLabel")){const d=document.createElement("div");d.id="activeGearLabel";d.className="gear-label";pet.after(d)}if(!$("#shopView")){const main=$("main.shell");const section=document.createElement("section");section.id="shopView";section.className="panel hidden";section.innerHTML='<div class="topbar"><div><strong>Hero Shop</strong><div id="shopSummary" class="muted"></div></div><button id="shopBackBtn" class="btn secondary">Back to Chapters</button></div><div id="shopGrid" class="shop-grid"></div>';main.insertBefore(section,$("#gameView"));$("#shopBackBtn").addEventListener("click",back)}}
function hideViews(){["loginView","lobbyView","heroView","petView","missionView","achievementView","teacherView","gameView","wrongBookView"].forEach(id=>$("#"+id)?.classList.add("hidden"))}
function openShop(){const p=active();if(!p)return;hideViews();$("#shopView").classList.remove("hidden");render()}
function back(){$("#shopView")?.classList.add("hidden");$("#lobbyView")?.classList.remove("hidden");const p=active();if(p)updateLobby(p)}
function render(){const p=ensure(active());if(!p)return;const equipped=ITEMS.find(x=>x.id===p.equippedGear);$("#shopSummary").textContent=`${p.coins||0} coins · ${equipped?`Equipped: ${equipped.name}`:"No gear equipped"}`;$("#shopGrid").innerHTML=ITEMS.map(item=>{const owned=p.inventory.includes(item.id),eq=p.equippedGear===item.id;let label=item.type==="consumable"?`Buy & Use · ${item.price}`:eq?"Equipped":owned?"Equip":`Buy · ${item.price}`;return `<article class="shop-card ${eq?'equipped':''}"><div class="shop-icon">${item.icon}</div><strong>${item.name}</strong><span>${item.type==='gear'?'Equipment':'Consumable'}</span><p>${item.desc}</p><button class="btn ${eq?'secondary':''}" data-shop="${item.id}" ${eq?'disabled':''}>${label}</button></article>`}).join("");document.querySelectorAll("[data-shop]").forEach(b=>b.addEventListener("click",()=>buyOrEquip(b.dataset.shop)))}
function buyOrEquip(id){const p=ensure(active()),item=ITEMS.find(x=>x.id===id);if(!p||!item)return;if(item.type==="gear"&&p.inventory.includes(id)){p.equippedGear=id;save(p);render();return}if((p.coins||0)<item.price){$("#shopSummary").textContent=`Not enough coins. You need ${item.price-(p.coins||0)} more.`;return}p.coins-=item.price;p.shopPurchases++;if(item.type==="gear"){p.inventory.push(id);p.equippedGear=id}else{p.xp=(p.xp||0)+(item.playerXp||0);p.heroXp=(p.heroXp||0)+(item.heroXp||0);p.petXp=(p.petXp||0)+(item.petXp||0);while(p.heroXp>=100){p.heroXp-=100;p.heroLevel=(p.heroLevel||1)+1}while(p.petXp>=60){p.petXp-=60;p.petLevel=(p.petLevel||1)+1}}save(p);render()}
function gearRewards(){const target=$("#feedback");if(!target)return;let last="";new MutationObserver(()=>{const text=target.textContent.trim();if(!text||text===last||!/attacks|Correct|Critical/i.test(text))return;last=text;const p=ensure(active()),item=ITEMS.find(x=>x.id===p.equippedGear);if(!p||!item||item.type!=="gear")return;p.xp=(p.xp||0)+(item.xp||0);p.coins=(p.coins||0)+(item.coins||0);save(p);if(item.xp||item.coins)target.textContent+=` · ${item.name} bonus +${item.xp||0} XP +${item.coins||0} coin${item.coins===1?'':'s'}`},{childList:true,subtree:true,characterData:true})}
window.addEventListener("DOMContentLoaded",()=>{document.title="F2 Math Hero V51.1";const h=document.querySelector(".hero h1");if(h)h.textContent="F2 Math Hero V51.1";inject();const p=active();if(p)updateLobby(ensure(p));gearRewards()});
})();