(()=>{"use strict";
const PROFILE_KEY="f2math_v50_profiles",ACTIVE_KEY="f2math_v50_active_student";
const $=s=>document.querySelector(s);
const REWARDS=[
 {day:1,coins:10,xp:10,label:"Starter Pack"},{day:2,coins:15,xp:15,label:"Quick Boost"},{day:3,coins:20,xp:20,label:"Bronze Chest"},{day:4,coins:25,xp:25,label:"Silver Chest"},{day:5,coins:30,xp:30,label:"Gold Chest"},{day:6,coins:40,xp:40,label:"Epic Chest"},{day:7,coins:60,xp:75,label:"Legend Chest"}
];
function profiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||"{}")||{}}catch{return {}}}
function active(){const name=localStorage.getItem(ACTIVE_KEY),all=profiles();return name?all[name]||null:null}
function save(p){const all=profiles();all[p.name]=p;localStorage.setItem(PROFILE_KEY,JSON.stringify(all));const xp=$("#playerXp"),coins=$("#playerCoins");if(xp)xp.textContent=p.xp||0;if(coins)coins.textContent=p.coins||0}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kuala_Lumpur",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function yesterday(){const d=new Date(Date.now()-86400000);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kuala_Lumpur",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function ensure(p){p.loginReward??={lastClaim:null,streak:0,totalClaims:0};return p}
function inject(){const row=$("#lobbyView .topbar .row");if(row&&!$("#rewardBtn")){const b=document.createElement("button");b.id="rewardBtn";b.className="btn secondary";b.textContent="Daily Reward";row.insertBefore(b,$("#missionBtn")||row.firstChild);b.addEventListener("click",open)}if(!$("#rewardView")){const main=$("main.shell"),section=document.createElement("section");section.id="rewardView";section.className="panel hidden";section.innerHTML='<div class="topbar"><div><strong>7-Day Login Rewards</strong><div id="rewardSummary" class="muted"></div></div><button id="rewardBackBtn" class="btn secondary">Back to Chapters</button></div><div id="rewardGrid" class="reward-grid"></div><div id="rewardMessage" class="feedback"></div>';main.insertBefore(section,$("#gameView"));$("#rewardBackBtn").addEventListener("click",back)}}
function hideViews(){["loginView","lobbyView","heroView","petView","missionView","achievementView","teacherView","shopView","gameView","wrongBookView"].forEach(id=>$("#"+id)?.classList.add("hidden"))}
function status(p){const r=ensure(p).loginReward,t=today();if(r.lastClaim===t)return {claimable:false,day:r.streak||1};let next=r.lastClaim===yesterday()?r.streak+1:1;if(next>7)next=1;return {claimable:true,day:next}}
function open(){const p=active();if(!p)return;hideViews();$("#rewardView").classList.remove("hidden");render()}
function back(){$("#rewardView")?.classList.add("hidden");$("#lobbyView")?.classList.remove("hidden")}
function render(){const p=ensure(active());if(!p)return;const s=status(p),r=p.loginReward;$("#rewardSummary").textContent=s.claimable?`Day ${s.day} reward is ready.`:`Reward claimed today · Current streak ${r.streak} day${r.streak===1?'':'s'}`;$("#rewardGrid").innerHTML=REWARDS.map(x=>{const current=x.day===s.day,claimed=!s.claimable&&x.day===r.streak;return `<article class="reward-card ${current?'current':''} ${claimed?'claimed':''}"><div class="reward-day">Day ${x.day}</div><div class="reward-chest">${x.day>=7?'🏆':x.day>=5?'🎁':'🧰'}</div><strong>${x.label}</strong><span>+${x.coins} coins · +${x.xp} XP</span>${current?`<button class="btn" id="claimDailyBtn" ${s.claimable?'':'disabled'}>${s.claimable?'Claim Reward':'Claimed Today'}</button>`:''}</article>`}).join("");$("#claimDailyBtn")?.addEventListener("click",claim)}
function claim(){const p=ensure(active()),s=status(p);if(!p||!s.claimable)return;const reward=REWARDS[s.day-1];p.loginReward.streak=s.day;p.loginReward.lastClaim=today();p.loginReward.totalClaims++;p.coins=(p.coins||0)+reward.coins;p.xp=(p.xp||0)+reward.xp;save(p);$("#rewardMessage").textContent=`${reward.label} opened! +${reward.coins} coins and +${reward.xp} XP.`;render()}
window.addEventListener("DOMContentLoaded",()=>{document.title="F2 Math Hero V51.2";const h=document.querySelector(".hero h1");if(h)h.textContent="F2 Math Hero V51.2";const p=document.querySelector(".hero p");if(p)p.textContent="Learning RPG with heroes, pets, battles, bosses, shop, daily rewards, missions, achievements, teacher tracking and audio feedback.";inject()});
})();